package dao.hibernate;

public class QueryConst
{
	public static final String VALID_USER_CHECK = 
			"SELECT USERID, PASSWORD FROM USERS WHERE USERID = ? AND PASSWORD = ?";
	public static final String UPDATE_USER_PWD = 
			"UPDATE USERS SET PASSWORD = ? WHERE USERID = ?";
	public static final String GET_ALL_ELIGIBLE_MATCHES = 
			"SELECT MATCHID, MATCHDATE, TEAM1, TEAM2, VENUE FROM MATCHES WHERE MATCHDATE > ?";
	public static final String GET_ALL_ELIGIBLE_MATCHES_WITH_ENDDATE = 
			"SELECT MATCHID, MATCHDATE, TEAM1, TEAM2, VENUE FROM MATCHES WHERE MATCHDATE BETWEEN ? AND ?";	
	public static final String CHECK_FOR_VALID_SAVE = 
			"SELECT * FROM MATCHES WHERE MATCHDATE <= ? AND MATCHID = ?";
	public static final String GET_ENTIRE_SCORECARD = "SELECT * FROM SCORECARD";
	public static final String GET_BEST_PREDICTION = 
			"SELECT SC.* FROM SCORECARD SC, (SELECT MAX(POINTS) MAXPOINTS, MATCHID FROM SCORECARD GROUP BY MATCHID) SC2 WHERE SC.MATCHID = SC2.MATCHID AND SC.POINTS =SC2.MAXPOINTS";
	public static final String GET_BEST_PREDICTION_FOR_THE_DAY = 
			"SELECT SC.* FROM SCORECARD SC, (SELECT MAX(POINTS) MAXPOINTS, MATCHID FROM SCORECARD WHERE MATCHDATE = ? GROUP BY MATCHID) SC2 WHERE SC.MATCHID = SC2.MATCHID AND SC.POINTS =SC2.MAXPOINTS";
	public static final String GET_BEST_PREDICTION_IN_SPECIFIED_RANGE = 
			"SELECT SC.* FROM SCORECARD SC, (SELECT MAX(POINTS) MAXPOINTS, MATCHID FROM SCORECARD WHERE MATCHDATE BETWEEN ? AND ? GROUP BY MATCHID) SC2 WHERE SC.MATCHID = SC2.MATCHID AND SC.POINTS =SC2.MAXPOINTS";

}
